import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,AlertTriangle,BrainCircuit,Factory,RefreshCw,Wrench} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
function App(){
 const [assets,setAssets]=useState([]),[stats,setStats]=useState({}),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [a,s]=await Promise.all([fetch(`${API}/assets`).then(r=>r.json()),fetch(`${API}/analytics`).then(r=>r.json())]);setAssets(a);setStats(s);setSelected(a.find(x=>x.risk==='High')||a[0]);}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const recommendation=selected? selected.risk==='High'?'Schedule an inspection within 24 hours. Investigate vibration and thermal load before the next operating cycle.':selected.risk==='Medium'?'Inspect during the next planned maintenance window and trend sensor readings.':'Continue normal monitoring; no immediate intervention indicated.':'';
 return <div className="app"><aside><div className="brand"><BrainCircuit/> <span>Asset<span>Ops</span></span></div><div className="nav active"><Activity/> Operations</div><div className="nav"><Factory/> Sites</div><div className="nav"><Wrench/> Work Orders</div><div className="nav"><BrainCircuit/> AI Insights</div><div className="side-note"><b>AI-FIRST WORKFLOW</b><p>Detect → Explain → Prioritise → Act</p></div></aside>
 <main><header><div><p className="eyebrow">XEMPLA • OPERATIONS CONTROL</p><h1>Asset Intelligence</h1><p className="muted">Live equipment health, anomaly signals and maintenance priorities.</p></div><button className="refresh" onClick={load}><RefreshCw size={16}/> Refresh</button></header>
 <section className="metrics"><Metric title="Active assets" value={stats.total||0} icon={<Factory/>}/><Metric title="Avg. health" value={`${stats.avgHealth||0}%`} icon={<Activity/>}/><Metric title="High risk" value={stats.critical||0} danger icon={<AlertTriangle/>}/><Metric title="Operational uptime" value={`${stats.uptime||0}%`} icon={<BrainCircuit/>}/></section>
 <section className="grid"><div className="panel"><div className="panel-head"><div><h2>Asset fleet</h2><span>{assets.length} monitored assets</span></div><span className="live">● LIVE</span></div>{loading?<p>Loading telemetry…</p>:<div className="table">{assets.map(a=><button className={`row ${selected?.id===a.id?'selected':''}`} key={a.id} onClick={()=>setSelected(a)}><div><b>{a.name}</b><small>{a.id} • {a.site}</small></div><div className="health"><strong>{a.health}%</strong><small>health</small></div><div className={`risk ${a.risk.toLowerCase()}`}>{a.risk}</div></button>)}</div>}</div>
 <div className="panel insight"><div className="panel-head"><div><h2>AI decision brief</h2><span>{selected?.id||'Select an asset'}</span></div><BrainCircuit/></div>{selected&&<><div className="score"><div className="circle"><strong>{selected.health}</strong><span>health</span></div><div><h3>{selected.name}</h3><p className="muted">{selected.type} • {selected.site}</p><div className="signal"><span>Temperature</span><b>{selected.temperature}°C</b></div><div className="signal"><span>Vibration</span><b>{selected.vibration} mm/s</b></div><div className="signal"><span>Load</span><b>{selected.load}%</b></div></div></div><div className={`alert ${selected.risk.toLowerCase()}`}><AlertTriangle size={18}/><div><b>{selected.risk} operational risk</b><p>{recommendation}</p></div></div><div className="explain"><b>Why this recommendation?</b><p>Risk is derived from health score and current operating signals. The recommendation is designed to be reviewed by an engineer before action.</p></div></>}</div></section>
 <footer>Prototype • Built with React, Node.js, MongoDB-ready APIs and AI service integration</footer></main></div>
}
function Metric({title,value,icon,danger}){return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{title}</span><strong className={danger?'danger':''}>{value}</strong></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
